### ISSUE TITLE
v0.8 로드맵

### ISSUE THREAD

**Issue by hotsixman** [taikowiki/taikowiki-svelte#161]
- [x] 단위 도장 추가/수정 기능 (#148)
- [x] 곡 상세 페이지에 유튜브 검색 링크 추가 (#46)

**Comment by hotsixman** [comment]
# 0.8.0
- [x] 단위 도장 추가 / 수정 및 과거 단위 추가(#164)

**Comment by hotsixman** [comment]
# 0.8.2
- [x] #172 (#173)
- [x] #46 (#174)

**Comment by hotsixman** [comment]
# 0.8.4
- [ ] #179
- [x] #195

**Comment by hotsixman** [comment]
# 0.8.5
- [ ] #179
- [x] 보면 이미지 로딩 추가(#200)
