### ISSUE TITLE
Version 0.4 로드맵

### ISSUE THREAD

**Issue by hotsixman** [taikowiki/taikowiki-svelte#24]
# version 0.4.0
- [x] 관리자 페이지 추가(2024-05-30)
    - [x] 곡 정보 수정, 추가 기능 추가(2024-05-30, #42)
    - [x] 곡 정보 수정 요청 허가/거부 기능 추가(2024-05-30, #42)
- [x] 유저 기능 추가(2024-05-30, #42)
- [x] 곡 정보 수정 요청 기능 추가(2024-05-30, #42)
- [x] #25 
- 버그 수정
    - [x] #33 
    - [x] #35
    - [x] #41

**Comment by hotsixman** [comment]
#48
#47
#42

**Comment by hotsixman** [comment]
#49

**Comment by hotsixman** [comment]
#50

**Comment by hotsixman** [comment]
#51

**Comment by hotsixman** [comment]
## version 0.4.0

- [x] 관리자 페이지 추가(2024-05-30)
    - [x] 곡 정보 수정, 추가 기능 추가(2024-05-30, #42)
    - [x] 곡 정보 수정 요청 허가/거부 기능 추가(2024-05-30, #42)
- [x] 유저 기능 추가(2024-05-30, #42)
- [x] 곡 정보 수정 요청 기능 추가(2024-05-30, #42)
- [x] #25 
- 버그 수정
    - [x] #33 
    - [x] #35
    - [x] #41

**Comment by hotsixman** [comment]
# 0.4.1
- [x] #45 
- [x] #65 
- [ ] #66
- [ ] #59
- [ ] #58 
- [ ] #36
